### ISSUE TITLE
Add output that can be used with another step or job

### ISSUE THREAD

**Issue by mr-pmillz** [pplotka/local-php-security-checker-github-actions#5]
I would like to use the output from local-php-security-checker using this github action.

Rather than adding the binary to my docker image or writing a script to download and run this binary myself,

if would be nice if there was an option to be used in the with block that can specify an output file.

Currently, it doesn't look like there is a good way to do this with this actions current state.

If there is a way to do this, can you include it in the README.md or add an output option to a file or variable that can be referenced.

I want to include the output of this in a slack notification. something like the following.
As a rough idea of what i'm trying to achieve.

```yaml
name: Security scanner

on: [push, pull_request]

jobs:
  security:
    name: Local PHP Security Checker
    runs-on: ubuntu-latest
    outputs:
     security: ${{ steps.local_php_security_checker.output }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Local PHP Security Checker
        id: local_php_security_checker
        uses: docker://pplotka/local-php-security-checker-github-actions
        with:
          format: markdown
          path: ./composer.lock

  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: FooBarBaz
        SLACK_MESSAGE: ${{ join(steps.local_php_security_checker.outputs.security, '\n') }}
        SLACK_TITLE: BarFoo
        SLACK_USERNAME: Foobar
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
```

How can I achieve this?

Awesome project by the way. I was getting ready to create similar project because i too want to use this as a github action in my workflow and then i found your project which is awesome!
Great work!!! 💯

**Comment by mr-pmillz** [comment]
Thank you so much! 💯

**Comment by pplotka** [comment]
Hi Phil! 

This is not a complete solution yet. I working on fixing it now so I reopen this issue. Sorry for the inconvenience ;-)

**Comment by pplotka** [comment]
Hi Phil! 

Sorry for the little chaos during the delivery solution. But finally, I think that the current solution is good enough to satisfy your needs. 

I've tested this solution with below workflow definition:

```yaml
name: Security scanner

on: [push, pull_request]

jobs:
  psalm:
    name: Local PHP Security Checker
    runs-on: ubuntu-latest
    outputs:
      security: ${{ steps.local_php_security_checker.outputs.security }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Local PHP Security Checker...
        id: local_php_security_checker
        uses: pplotka/local-php-security-checker-github-actions@1.1.1
        with:
          format: markdown
          path: composer-fixed.lock
          
      - name: Output
        run: echo "${{ steps.local_php_security_checker.outputs.security }}"
       

  output:  
    name: Output
    needs: psalm
    runs-on: ubuntu-latest
    steps:
      - name: Display the output
        run: echo "${{needs.psalm.outputs.security}}"
```

I think this should help you with your task.
