### ISSUE TITLE
Output no longer shows by default and unable to get output

### ISSUE THREAD

**Issue by mr-pmillz** [pplotka/local-php-security-checker-github-actions#9]
using this code, the output is empty and no output shows anywhere. using similar example from readme.

```yaml
name: Security scanner

on: [push, pull_request]

jobs:
  security-checker:
    name: Local PHP Security Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Local PHP Security Checker
        id: local_php_security_checker
        continue-on-error: true
        uses: docker://pplotka/local-php-security-checker-github-actions:latest
        with:
          format: markdown

      - name: Security Checker Output
        id: security_output
        run: |
          echo "${{ steps.local_php_security_checker.outputs.security }}"
          echo "${{ steps.local_php_security_checker.outputs.security }}" > security_checker_output.log
          echo "::set-output name=sec_msg::$(cat security_checker_output.log)"

      - name: Check if Vulns exist
        id: vulns_exist
        run: |
          if grep -q "No packages have known vulnerabilities" security_checker_output.log; then
          echo "::set-output name=found_vulns::false"
          else
          echo "::set-output name=found_vulns::true"
          fi

      - name: Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2
        if: "${{ steps.vulns_exist.outputs.found_vulns == 'true' }}"
        env:
          SLACK_CHANNEL: foobarbaz
          SLACK_COLOR: "${{ job.status == 'success' && 'good' || 'danger' }}"
          SLACK_MESSAGE: ${{ steps.security_output.outputs.sec_msg }}
          SLACK_TITLE: PHP SECURITY ISSUES FOUND
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_LINK_NAMES: true
```

except no output is shown anywhere from any of the steps or from running image locally, with docker,
```shell
docker run --rm -it -w /app -v $(pwd):/app pplotka/local-php-security-checker-github-actions --format=yaml
```

gives no output.

it should give output by default and also have output option.
Would be nice if had an argument in action.yml specifying output file or output env var that would go into >> $GITHUB_ENV
or something that could be referenced.

Also if you had a working slack reporting example in the readme that would be cool.

Appreciate you looking into this! 💯
